version: '3.3'
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    env_file: .env
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
